mariadb:
  enabled: true
  primary:
    ## Enable persistence using Persistent Volume Claims
    ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
    ##
    persistence:
      ## Name of existing PVC to hold MariaDB Primary data
      ## NOTE: When it's set the rest of persistence parameters are ignored
      ##
      existingClaim: directus-db-pvc

redis:
  enabled: true
  master:
    persistence:
      enabled: true
      existingClaim: directus-redis-master-pvc
  replica:
    replicaCount: 1
    persistence:
      enabled: true
      existingClaim: directus-redis-replica-pvc

