# An array to add extra environment variables
extraEnvVars:
- name: KEY
  value: "1"
- name: SECRET
  value: "pippo!@#"
- name: ADMIN_PASSWORD
  value: "d1r3ctu5"
# Going postgreSQL
- name: DB_CLIENT
  value: "pg"
- name: DB_CONNECTION_STRING
  value: "postgresql://directus:d1r3ctu5@directus-postgresql:5432/directus"
- name: NODE_TLS_REJECT_UNAUTHORIZED
  value: "0"

#Expose directus via ingress, requires nginx ingress in your dev kubernetes
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: public
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: directus.local
      paths:
      - path: /
        backend:
          serviceName: directus
          servicePort: 80
        pathType: ImplementationSpecific
  tls: []

postgresql:
  enabled: true
  auth:
    ## @param auth.enablePostgresUser Assign a password to the "postgres" admin user. Otherwise, remote access will be blocked for this user
    ##
    enablePostgresUser: true
    ## @param auth.postgresPassword Password for the "postgres" admin user. Ignored if `auth.existingSecret` is provided
    ##
    # postgresPassword: "diomerda"
    ## @param auth.username Name for a custom user to create
    ##
    username: "directus"
    ## @param auth.password Password for the custom user to create. Ignored if `auth.existingSecret` is provided
    ##
    password: "d1r3ctu5"
    ## @param auth.database Name for a custom database to create
    ##
    database: "directus"
    ## @param auth.replicationUsername Name of the replication user
    ##  
  primary:
    ## Enable persistence using Persistent Volume Claims
    ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
    ##
    persistence:
      ## Name of existing PVC to hold MariaDB Primary data
      ## NOTE: When it's set the rest of persistence parameters are ignored
      ##
      existingClaim: directus-db-postgre-pvc
    extraEnvVars:
    - name: POSTGRESQL_LOG_HOSTNAME
      value: "true"
    - name: POSTGRESQL_LOG_CONNECTIONS
      value: "true"
    pgHbaConfiguration: |-
      local all all trust
      host all all ::1/128 trust
      host directus dir_db 10.0.0.0/8 trust
      host all all 0.0.0.0/0 trust

mariadb:
  enabled: false

redis:
  enabled: true
  master:
    persistence:
      enabled: true
      existingClaim: directus-redis-master-pvc
  replica:
    replicaCount: 1
    persistence:
      enabled: true
      existingClaim: directus-redis-replica-pvc

# GRANT ALL ON SCHEMA public TO directus;
# grant all privileges on database directus to directus;