apiVersion: v1
kind: PersistentVolume
metadata:
  name: directus-db-postgre-volume
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/dockerdata/directus/postgresql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: directus-db-postgre-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi